/* auto-generated by scripts/bump-app-update.cjs — do not edit */
export const APP_VERSION = "1.1.27";
export const APP_ICONS = {
  "favicon": "/icons/v1.1.27/favicon.png",
  "icon192": "/icons/v1.1.27/icon-192.png",
  "icon512": "/icons/v1.1.27/icon-512.png",
  "apple": "/icons/v1.1.27/apple-touch-icon.png",
  "logo": "/icons/v1.1.27/logo.jpg"
} as const;
export const APP_THEME_COLOR = '#b91c1c';
