/* auto-generated by scripts/bump-app-update.cjs — do not edit */
export const APP_VERSION = "1.1.2609291325";
export const APP_ICONS = {
  "favicon": "/icons/v1.1.2609291325/favicon.png",
  "icon192": "/icons/v1.1.2609291325/icon-192.png",
  "icon512": "/icons/v1.1.2609291325/icon-512.png",
  "apple": "/icons/v1.1.2609291325/apple-touch-icon.png",
  "logo": "/icons/v1.1.2609291325/logo.jpg"
} as const;
export const APP_THEME_COLOR = '#1d4ed8';
